### ISSUE TITLE
Mechanism to rotate logs externally

### ISSUE THREAD

**Issue by DRVTiny** [polettix/Log-Log4perl-Tiny#7]
Please, add $logger's object method to  reopen all filehandlers. This is needed to make it possible to rotate logs externally. 

Such mechanism present in Log::Log4perl, but i prefer to use your module.

Thank you!

**Comment by polettix** [comment]
Hi!

Log::Log4perl does support rotation through proper configuration of the appender. As Log::Log4perl::Tiny does not support appenders, it's impossible to expose the exact same functionality with the same interface.

**BUT**.

To cope with lack of appenders and all other goodies, Log::Log4perl::Tiny provides some flexibility through method [`fh`](https://metacpan.org/pod/Log::Log4perl::Tiny#fh2). This gives you most of the tools you need, but it also makes it difficult to provide a generic "reopen" capability because the things you can set are quite generic.

The easiest way I can think of can use the already present machinery and obtain something that should suit your needs. For example (untested), you might want to call this *after* doing the log rotation:

    sub reopen_logs {
        get_logger->fh(build_channels(file_append => $ENV{LOG_FILEPATH}));
    }

    # in case...
    $SIG{USR1} = sub { reopen_logs() };

The previous stuff registered in `fh` will be thrown away and this should also trigger the closure of the *old* file.

Another alternative that can give you finer control is to set a sub reference and do some things inside. Example (again, untested):

    get_logger->fh(\&emit_log);
    my $CLOSE_LOG;
    $SIG{USR1} = sub { $CLOSE_LOG = 1 };
    # ... or just set $CLOSE_LOG to 1 whenever you need to do close-then-reopen
    {
        my $fh;
        sub close_log {
            close $fh or warn "close(): $!";
            $fh = undef;
            return;
        }
        sub open_log {
            open $fh, '>', $ENV{LOG_FILEPATH} or die "open(): $!";
        }
        sub emit_log {
            $CLOSE_LOG = close_log() if $fh && $CLOSE_LOG;
            open_log() unless $fh;
            print {$fh} $_[0];
        }
    }

**Comment by polettix** [comment]
Didn't see any activity here, I'll close the issue. Re-open it if you want to discuss further.
